# Generated by Django 6.0.1 on 2026-04-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('long_desc', models.TextField(blank=True, default='')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('platform', models.CharField(default='PC', max_length=100)),
                ('url', models.URLField(blank=True, default='')),
                ('img', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming'), ('development', 'In Development')], default='upcoming', max_length=20)),
                ('release_date', models.CharField(blank=True, default='', max_length=50)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudioSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(default='Doppa Games', max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram', models.CharField(blank=True, max_length=255)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('about_title', models.CharField(blank=True, max_length=255)),
                ('about_p1', models.TextField(blank=True)),
                ('about_p2', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Studio Settings',
            },
        ),
    ]
